## Assesment 1)

## Importing Pandas and Numpy

In [1]:
import pandas as pd
import numpy as np

## Loading the Dataset

In [2]:
df=pd.read_csv('cric_data.tsv', delimiter='\t')
print(df.head(20))


    Unnamed: 0  Sachin Tendulkar  Rahul Dravid  India
0            0               100            78    342
1            1                11            62    191
2            2                 8            85    252
3            3                71            24    307
4            4               104            17    229
5            5                18           104    246
6            6                 8            76    226
7            7                86            74    288
8            8                12            60    216
9            9                85            12    224
10          10                18            63    161
11          11                 4           107    276
12          12                 7            76    283
13          13                37             4    297
14          14                14             5    139
15          15                 0            33    224
16          16                 4             7    178
17          17              

## performing basic statistical functions
## Finding Mean Scores by Sachin,Rahul and Indian Players
## Finding Maximum Scores recorded by Sachin and Rahul

In [3]:
data = np.genfromtxt('cric_data.tsv', delimiter='\t', skip_header=1, filling_values=np.nan)
sachin_scores = data[:, 0]
dravid_scores = data[:, 1]
india_scores = data[:, 2]
sachin_mean = np.mean(sachin_scores)
dravid_mean = np.mean(dravid_scores)
india_mean = np.mean(india_scores)
print("Mean score by Sachin Tendulkar: ", sachin_mean)
print("Mean score by Rahul Dravid: ", dravid_mean)
print("Mean score by India: ", india_mean)
sachin_max = np.max(sachin_scores)
rahul_max = np.max(dravid_scores)
print("Maximum score by Sachin: ", sachin_max)
print("Maximum score by Rahul: ", rahul_max)

Mean score by Sachin Tendulkar:  112.0
Mean score by Rahul Dravid:  39.87555555555556
Mean score by India:  32.062222222222225
Maximum score by Sachin:  224.0
Maximum score by Rahul:  186.0


##  Various ways of Numpy Array Creation

In [4]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))


arr = np.array((1, 2, 3, 4, 5))

print(arr)

arr = np.array(18)

print(arr)

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)


arr = np.array([1, 2, 3, 4, 5])

print(arr)


arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]
18
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Assessment 2

## Compare and Contast Lists and Arrays

In [5]:
import numpy as np
my_list = [1, 2, 3, 4, 5]

# creating an array
my_array = np.array([1, 2, 3, 4, 5])

# accessing elements
print(my_list[0])     
print(my_array[0])    
# slicing
print(my_list[1:3])   
print(my_array[1:3])  

# concatenation
new_list = my_list + [6, 7, 8]
new_array = np.concatenate((my_array, [6, 7, 8]))

# appending
my_list.append(6)
my_array = np.append(my_array, 6)

# removing elements
my_list.remove(3)
my_array = np.delete(my_array, 2)

# size
print(len(my_list))    
print(my_array.size)   

# data type
print(type(my_list[0]))        
print(type(my_array[0]))       

# arithmetic operations
new_list = [x + 1 for x in my_list]
new_array = my_array + 1


1
1
[2, 3]
[2 3]
5
5
<class 'int'>
<class 'numpy.int32'>


## Show the benefits of using arrays over lists evidentially.

In [6]:
import sys
import numpy as np

# create a list of 1000 elements
my_list = range(1000)

# create an array of 1000 elements
my_array = np.arange(1000)

# calculate the memory used by the list
list_size = sys.getsizeof(1) * len(my_list)
print("Memory used by the list:", list_size, "bytes")

# calculate the memory used by the array
array_size = my_array.nbytes
print("Memory used by the array:", array_size, "bytes")

import numpy as np

# create two arrays
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# matrix multiplication using arrays
C = np.dot(A, B)
print(C)


Memory used by the list: 28000 bytes
Memory used by the array: 4000 bytes
[[19 22]
 [43 50]]


## Define Dictionary with Employee data and use the same in Data Frame creation.

In [7]:
import pandas as pd

employee_data = {'Name': ['Raja', 'Adrein', 'Nikitha','Akalya','Virushka','Vamika'],
                 'Age': [25, 30, 35,26,31,24],
                 'Salary': [50000, 60000, 70000,65000,38000,66000]}

df = pd.DataFrame(employee_data)


print(df)


       Name  Age  Salary
0      Raja   25   50000
1    Adrein   30   60000
2   Nikitha   35   70000
3    Akalya   26   65000
4  Virushka   31   38000
5    Vamika   24   66000


## Define a class with constructor, method process with objects.

In [8]:
class MyClass:
    def __init__(self, x, y):
        self.x = x
        self.y = y
    
    def process(self):
        return self.x + self.y

# Creating objects of MyClass
obj1 = MyClass(2, 3)
obj2 = MyClass(5, 7)

# Calling the process method on objects
result1 = obj1.process()
result2 = obj2.process()

print(result1)  # Output: 5
print(result2)  # Output: 12


5
12


##  In this example, we defined a class MyClass with a constructor that initializes two instance variables x and y. We also defined a method process which adds the values of x and y and returns the result. We then created two objects obj1 and obj2 of MyClass and called the process method on these objects to get the result.

## List Comprehension in Python

In [9]:
# Create a list of squares of numbers from 1 to 10 using list comprehension
squares = [x**2 for x in range(1, 11)]
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


## Dictionary Comprehension in Python

In [10]:
# Create a dictionary of squares of numbers from 1 to 10 using dictionary comprehension
squares_dict = {x: x**2 for x in range(1, 11)}
print(squares_dict)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


# Assesment 3

In [11]:
import pandas as pd
import seaborn as sns
import numpy as np

## Loading the dataset

In [12]:
planets_df = sns.load_dataset('planets')

print(planets_df.head())

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009


## Performing info() and describe() operations

In [13]:
planets_df.info()
planets_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   method          1035 non-null   object 
 1   number          1035 non-null   int64  
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64  
dtypes: float64(3), int64(2), object(1)
memory usage: 48.6+ KB


number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

## Adding a new row and column

In [26]:
# Add a new column called "distance_in_km" with random values
planets_df["distance_in_km"] = [i for i in range(1034)]

# Add a new row to the DataFrame
new_row = {"method": "Transit", "number": 1, "orbital_period": 1.1, "mass": 1.2, "distance": 1.3, "year": 2000, "distance_in_km": 300000}
planets_df = planets_df.append(new_row, ignore_index=True)
planets_df

C:\Users\Rajagopal\AppData\Local\Temp\ipykernel_8292\975853913.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  planets_df = planets_df.append(new_row, ignore_index=True)


method  number  orbital_period   mass  distance  year  \
0     Radial Velocity       1      269.300000   7.10     77.40  2006   
1     Radial Velocity       1      874.774000   2.21     56.95  2008   
2     Radial Velocity       1      763.000000   2.60     19.84  2011   
3     Radial Velocity       1      326.030000  19.40    110.62  2007   
4     Radial Velocity       1      516.220000  10.50    119.47  2009   
...               ...     ...             ...    ...       ...   ...   
1030          Transit       1        3.941507    NaN    172.00  2006   
1031          Transit       1        2.615864    NaN    148.00  2007   
1032          Transit       1        3.191524    NaN    174.00  2007   
1033          Transit       1        4.125083    NaN    293.00  2008   
1034          Transit       1        1.100000   1.20      1.30  2000   

      distance_in_km  
0                  0  
1                  1  
2                  2  
3                  3  
4                  4  
...              ...  
1030            1030  
1031            1031  
1032            1032  
1033            1033  
1034          300000  

[1035 rows x 7 columns]

In [ ]:
planets_df

## Drop rows

In [23]:
planets_df = planets_df.drop(planets_df.tail(1).index)
planets_df

method  number  orbital_period   mass  distance  year  \
0     Radial Velocity       1      269.300000   7.10     77.40  2006   
1     Radial Velocity       1      874.774000   2.21     56.95  2008   
2     Radial Velocity       1      763.000000   2.60     19.84  2011   
3     Radial Velocity       1      326.030000  19.40    110.62  2007   
4     Radial Velocity       1      516.220000  10.50    119.47  2009   
...               ...     ...             ...    ...       ...   ...   
1029          Imaging       1             NaN    NaN     10.10  2012   
1030          Transit       1        3.941507    NaN    172.00  2006   
1031          Transit       1        2.615864    NaN    148.00  2007   
1032          Transit       1        3.191524    NaN    174.00  2007   
1033          Transit       1        4.125083    NaN    293.00  2008   

      distance_in_km  
0                  0  
1                  1  
2                  2  
3                  3  
4                  4  
...              ...  
1029            1029  
1030            1030  
1031            1031  
1032            1032  
1033            1033  

[1034 rows x 7 columns]

## Drop columns

In [24]:
planets_df = planets_df.drop("distance_in_km", axis=1)
planets_df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1029          Imaging       1             NaN    NaN     10.10  2012
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008

[1034 rows x 6 columns]

## Perform some NumPy operations like finding out mean , max and min operations

In [15]:
# Mean
mean_distance = np.mean(planets_df["distance"])
print("Mean distance:", mean_distance)

# Max
max_mass = np.max(planets_df["mass"])
print("Maximum mass:", max_mass)

# Min
min_orbital_period = np.min(planets_df["orbital_period"])
print("Minimum orbital period:", min_orbital_period)

Mean distance: 264.06928217821786
Maximum mass: 25.0
Minimum orbital period: 0.09070629


## Assessment 4

## Loading the Dataset

In [ ]:
df=pd.read_csv('titanic_dataset.csv', delimiter=',')
df.head()

## Clean the continuous Variables.
##  Drop unnecessary variables.
## Clean Categorical Variables by fill in Missing.
## Storing the Cleaned Data.

In [ ]:


# Drop unnecessary variables
df = df.drop(['Name', 'Ticket', 'Cabin'], axis=1)

# Clean the continuous variables
mean_age = df['Age'].mean()
df['Age'].fillna(mean_age, inplace=True)

mean_fare = df['Fare'].mean()
df['Fare'].fillna(mean_fare, inplace=True)

# Clean categorical variables by fill in missing

sex_mode = df['Sex'].mode()[0]
df['Sex'].fillna(sex_mode, inplace=True)

mode_embarked = df['Embarked'].mode().iloc[0]
df['Embarked'].fillna(mode_embarked, inplace=True)

# Store the cleaned data
df.to_csv('cleaned_titanic_dataset.csv', index=False)

# Print the cleaned dataset
print(df.head())

